name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --index-url https://download.pytorch.org/whl/cpu
          pip install -r dev-requirements.txt
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Tests
        run: |
          pytest -q
